ADMISSION_FEATURES = {
    "polllution": [
        "AQI",
        "PM2.5 AVG",
        "PM2.5 MIN",
        "PM2.5 MAX",
        "PM10 AVG",
        "PM10 MIN",
        "PM10 MAX",
        "NO2 AVG",
        "NO2 MIN",
        "NO2 MAX",
        "NH3 AVG",
        "NH3 MIN",
        "NH3 MAX",
        "SO2 AVG",
        "SO2 MIN",
        "SO2 MAX",
        "CO AVG",
        "CO MIN",
        "CO MAX",
        "OZONE AVG",
        "OZONE MIN",
        "OZONE MAX",
        "PROMINENT POLLUTENT",
        "MAX TEMP",
        "MIN TEMP",
        "HUMIDITY",
    ],
    "medical": [
        "SMOKING ",
        "ALCOHOL",
        "DM",
        "HTN",
        "CAD",
        "PRIOR CMP",
        "CKD",
        "HB",
        "TLC",
        "PLATELETS",
        "GLUCOSE",
        "UREA",
        "CREATININE",
        "BNP",
        "RAISED CARDIAC ENZYMES",
        "EF",
        "SEVERE ANAEMIA",
        "ANAEMIA",
        "STABLE ANGINA",
        "ACS",
        "STEMI",
        "ATYPICAL CHEST PAIN",
        "HEART FAILURE",
        "HFREF",
        "HFNEF",
        "VALVULAR",
        "CHB",
        "SSS",
        "AKI",
        "CVA INFRACT",
        "CVA BLEED",
        "AF",
        "VT",
        "PSVT",
        "CONGENITAL",
        "UTI",
        "NEURO CARDIOGENIC SYNCOPE",
        "ORTHOSTATIC",
        "INFECTIVE ENDOCARDITIS",
        "DVT",
        "CARDIOGENIC SHOCK",
        "SHOCK",
        "PULMONARY EMBOLISM",
        "CHEST INFECTION",
    ],
    "time": [
        "D.O.A",
        "D.O.D",
        "DATE OF BROUGHT DEAD",
        "DURATION OF STAY",
        "duration of intensive unit stay",
    ],
    "demographic": ["AGE", "GENDER", "RURAL"],
    "admission": ["MRD No.", "TYPE OF ADMISSION-EMERGENCY/OPD", "OUTCOME"],
}
